name: tots_challenge
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  app_client:
    path: packages/app_client
  bloc: ^8.1.2
  cupertino_icons: ^1.0.0
  data_persistence:
    path: packages/data_persistence
  dio: ^5.4.0
  dotted_decoration: ^2.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.9
  get_it: ^7.6.4
  go_router: ^12.1.1
  image_picker: ^1.0.4
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.0
  sizer: ^2.0.15
  ui:
    path: packages/ui

dev_dependencies:
  bloc_test: ^9.1.4
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans/DMSans-Black.ttf
          weight: 900
        - asset: assets/fonts/DMSans/DMSans-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/DMSans/DMSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/DMSans/DMSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/DMSans/DMSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/DMSans/DMSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/DMSans/DMSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/DMSans/DMSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/DMSans/DMSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/DMSans/DMSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/DMSans/DMSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/DMSans/DMSans-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/DMSans/DMSans-Light.ttf
          weight: 300
        - asset: assets/fonts/DMSans/DMSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/DMSans/DMSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/DMSans/DMSans-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/DMSans/DMSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/DMSans/DMSans-ThinItalic.ttf
          weight: 100
          style: italic
