name: app_client
description: This repository handles all the client requests to the API.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.1.2

dependencies:
  build_runner: ^2.4.6
  dio: ^5.4.0
  equatable: ^2.0.5
  hive: ^2.2.3
  http: ^1.1.0

dev_dependencies:
  hive_generator: ^2.0.1
  lints: ^2.0.0
  test: ^1.21.0
  very_good_analysis: ^5.1.0
