name: ui
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.1.2
  flutter: ">=1.17.0"

dependencies:
  blur: ^3.1.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  sizer: ^2.0.15
  top_snackbar_flutter: ^3.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  very_good_analysis: ^5.1.0
