name: data_persistence
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.1.2

dependencies:
  app_client:
    path: ../app_client
  hive: ^2.2.3
  path_provider: ^2.1.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  very_good_analysis: ^5.1.0
